* Added locking using flock to avoid multiple launches. README updated.

diff --git a/php-relaunch b/php-relaunch
--- a/php-relaunch
+++ b/php-relaunch
@@ -23,13 +23,23 @@
 
 # THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 # IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
+# FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT.  IN NO EVENT SHALL
 # THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 # LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 # FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 # DEALINGS IN THE SOFTWARE.
 
 SCRIPTNAME=${0##*/}
+
+## The lock to be used for avoiding multiple launches.
+if [ $(id -u) -eq 0 ]; then
+    LOCKFILE=/var/run/lock/$SCRIPTNAME.lock
+else
+    LOCKFILE=/tmp/$SCRIPTNAME.lock
+fi
+
+## Create a sub shell with the file descriptor that handles the locking.
+exec 8>$LOCKFILE
 
 ## Check the number of arguments.
 [ $# -lt 3 ] && echo "Usage: $SCRIPTNAME <URI> <response timeout> <email address> [restart CGI]" && exit 1
@@ -55,6 +65,9 @@ PGREP=$(which pgrep)
 SERVICE=/usr/sbin/service
 [ -x $SERVICE ] || exit 0
 
+FLOCK=$(which flock)
+[ -x $FLOCK ] || exit 0
+
 ## Relaunch the PHP process.
 function relaunch_php() {
     ## Kill the php-fpm process.
@@ -65,6 +78,12 @@ function relaunch_php() {
     ## If the process didn't start try to relaunch it successively.
     while [ $LAUNCH_ATTEMPS -lt $MAX_LAUNCH_ATTEMPTS ]; do
         $SERVICE $1 start
+        ## Give some time for it to come up.
+        sleep 2
+        ## If it's already running break out.
+        if  ($PGREP $1 &>/dev/null); then
+            break
+        fi
         LAUNCH_ATTEMPS=$((LAUNCH_ATTEMPS + 1))
     done
 }
@@ -86,7 +105,7 @@ MAILX=$(which mailx)
 [ -x $MAILX ] || exit 0
 
 ## Log file.
-LOG_FILE=/tmp/php_relaunch.log
+LOG_FILE=/tmp/php-relaunch.log
 
 ## Get a timestamp using ts from the moreutils package.
 TS=$(which ts)
@@ -99,41 +118,46 @@ RESPONSE_TIMEOUT=$2
 ## (seconds) is the dividend.
 INTERVAL=$((60 / RESPONSE_TIMEOUT))
 
+## Use a lock to avoid multiple launches.
+if $FLOCK -n 8; then
 ## Looping over the number of divisions in a minute.
-for i in $(seq 1 $INTERVAL); do
-    ## Perform the request and check the response.
-    TS_BEGIN_REQUEST=$(date '+ %s')
-    STATUS_CODE=$($CURL_PROG -I -s -m $RESPONSE_TIMEOUT $1 | sed -n '/^HTTP\/1\.1/p' | awk '{print $2}')
-    ## Exit immediately if we can't connect to host. Exit status 7.
-    [ $? -eq 7 ] && exit 7
-    TS_END_REQUEST=$(date '+ %s')
+    for i in $(seq 1 $INTERVAL); do
+        ## Perform the request and check the response.
+        TS_BEGIN_REQUEST=$(date '+ %s')
+        STATUS_CODE=$($CURL_PROG -I -s -m $RESPONSE_TIMEOUT $1 | sed -n '/^HTTP\/1\.1/p' | awk '{print $2}')
+        ## Exit immediately if we can't connect to host. Exit status 7.
+        [ $? -eq 7 ] && exit 7
+        TS_END_REQUEST=$(date '+ %s')
 
-    ## Acting on the HTTP status code returned.
-    case $STATUS_CODE in
-        500|502|503|504|"")
-            ## PHP is dead, kill and restart it.
-            relaunch_php $PHP_FPM_NAME # php-fpm
-            ## Restart php-cgi only if there's a fourth argument.
-            if [ $# -eq 4 ]; then
-                ## The php-cgi program.
-                PHP_CGI=/usr/bin/php5-cgi
-                [ -x $PHP_CGI ] || exit 0
-                ## Get the php-cgi program name.
-                PHP_CGI_NAME=$(basename $PHP_CGI)
-                relaunch_php $PHP_CGI_NAME # php-cgi
-            fi
-            ## Log the restart and send an alert.
-            LOG_LINE="$HOSTNAME $STATUS_CODE PHP restarted."
-            echo $LOG_LINE | $TS >> $LOG_FILE
-            ## Send an email only if the address is a non null string.
-            [ -n "$3" ] && (echo $LOG_LINE | $TS | $MAILX -s "$HOSTNAME PHP restart" "$3")
-            sleep $(max $RESPONSE_TIMEOUT 10)  # give some time to normalize things
-            ;;
-        200)
-            ## Sleep for some time based on the request duration and the
-            ## specified response timeout.
-            SLEEP_VALUE=$((RESPONSE_TIMEOUT - TS_END_REQUEST + TS_BEGIN_REQUEST))
-            [ $SLEEP_VALUE -gt 0 ] && sleep $SLEEP_VALUE
-            ;;
-    esac
-done
+        ## Acting on the HTTP status code returned.
+        case $STATUS_CODE in
+            500|502|503|504|"")
+                ## PHP is dead, kill and restart it.
+                relaunch_php $PHP_FPM_NAME # php-fpm
+                ## Restart php-cgi only if there's a fourth argument.
+                if [ $# -eq 4 ]; then
+                    ## The php-cgi program.
+                    PHP_CGI=/usr/bin/php5-cgi
+                    [ -x $PHP_CGI ] || exit 0
+                    ## Get the php-cgi program name.
+                    PHP_CGI_NAME=$(basename $PHP_CGI)
+                    relaunch_php $PHP_CGI_NAME # php-cgi
+                fi
+
+                ## Log the restart and send an alert.
+                LOG_LINE="$HOSTNAME $STATUS_CODE PHP restarted."
+                echo $LOG_LINE | $TS >> $LOG_FILE
+                ## Send an email only if the address is a non null string.
+                [ -n "$3" ] && (echo $LOG_LINE | $TS | $MAILX -s "$HOSTNAME PHP restart" "$3")
+                sleep $(max $RESPONSE_TIMEOUT 10)  # give some time to normalize things
+                ;;
+            200)
+                ## Sleep for some time based on the request duration and the
+                ## specified response timeout.
+                SLEEP_VALUE=$((RESPONSE_TIMEOUT - TS_END_REQUEST + TS_BEGIN_REQUEST))
+                [ $SLEEP_VALUE -gt 0 ] && sleep $SLEEP_VALUE
+                ;;
+        esac # case
+    done # for
+fi # flock
+
